In [1]:
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
from random import random

In [2]:
np.array(1)

array(1)

In [3]:
import os

In [4]:
from lcmcmc.utils import get_data_dir_path

In [5]:
from kndetect.utils import load_pcs

In [6]:
import tensorflow as tf
import tensorflow_probability as tfp

2023-08-03 16:44:08.174244: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-03 16:44:08.179950: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-03 16:44:08.251885: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-03 16:44:08.253040: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-03 16:44:10.706356: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

# Build covariance matrix

In [7]:
features = pd.read_csv(os.path.join(get_data_dir_path(), "complete_lc_features.csv"))

In [8]:
num_coeffs = 3
bands = ['g', 'r']

col_names = []
for band in bands:
    for coeff_num in range(num_coeffs):
        col_names.append(f"coeff{coeff_num+1}_{band}")

In [10]:
kn_features = features[features["y_true"].values][col_names]

In [12]:
mu = kn_features.mean().values
cov = kn_features.cov().values
scale = tf.linalg.cholesky(cov)

In [20]:
cov

array([[ 0.03853426,  0.00159615, -0.00296206,  0.02164706,  0.00262403,
        -0.00039953],
       [ 0.00159615,  0.01130182, -0.00638567,  0.00315091,  0.00268014,
        -0.00346832],
       [-0.00296206, -0.00638567,  0.02264032, -0.00063753, -0.0031877 ,
         0.0147698 ],
       [ 0.02164706,  0.00315091, -0.00063753,  0.03937759,  0.00235727,
        -0.00357844],
       [ 0.00262403,  0.00268014, -0.0031877 ,  0.00235727,  0.01048252,
        -0.00696544],
       [-0.00039953, -0.00346832,  0.0147698 , -0.00357844, -0.00696544,
         0.02520785]])

In [18]:
mu

array([ 0.39193607,  0.14900582, -0.00897937,  0.47276811,  0.13964261,
       -0.00791459])

In [17]:
scale

<tf.Tensor: shape=(6, 6), dtype=float64, numpy=
array([[ 0.19630145,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.00813113,  0.10599862,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.01508937, -0.05908546,  0.13755559,  0.        ,  0.        ,
         0.        ],
       [ 0.11027457,  0.02126683,  0.01659698,  0.16275556,  0.        ,
         0.        ],
       [ 0.01336737,  0.02425928, -0.01128722,  0.00340762,  0.09785864,
         0.        ],
       [-0.00203527, -0.03256425,  0.09316243, -0.02585272, -0.05118206,
         0.11034524]])>

In [15]:
np.save(os.path.join(get_data_dir_path(), "scale"), scale) 

In [16]:
np.save(os.path.join(get_data_dir_path(), "mu"), mu) 